### ISSUE TITLE
Class constructor PluginClient cannot be invoked @0.2.3-alpha.4

### ISSUE THREAD

**Issue by kingcent** [ethereum/remixd#124]
When run remixd -s ./ --remix-ide https://remix.ethereum.org, will get error below, but fixed if install 0.2.3-alpha.3
--------------------
/Users/kc/.nvm/versions/node/v8.15.1/lib/node_modules/remixd/lib/bin/remixd.js:35
        throw new Error(error);
        ^

Error: TypeError: Class constructor PluginClient cannot be invoked without 'new'
    at Object.<anonymous> (/Users/kc/.nvm/versions/node/v8.15.1/lib/node_modules/remixd/lib/bin/remixd.js:35:15)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3

**Comment by bertmiller** [comment]
Getting the same error as you.

**Comment by phonegapX** [comment]
Getting the same error too

**Comment by ioedeveloper** [comment]
@kingcent upgrading to v0.2.3-alpha.7 fixes this issue.
