### ISSUE TITLE
Runtime error while executing remixd command

### ISSUE THREAD

**Issue by kooshansari** [ethereum/remixd#31]
I am not able to execute the remixd command as per in the readme file and it is showing the error as follows.
/usr/local/lib/node_modules/remixd/src/router.js:4
class Router {
^^^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/remixd/src/main.js:2:14)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)

My system configuration is:
Distributor ID:	LinuxMint
Description:	Linux Mint 18.3 Sylvia
Release:	18.3
Codename:	sylvia
npm version = 3.5.2
node version = 4.2.6

**Comment by ioedeveloper** [comment]
Please update your remixd version to the latest (v0.2.4-alpha.0) and let us know if it fixes this problem for you. @kooshansari
